# استفاده از ایمیج رسمی پایتون
FROM python:3.10-slim

# تنظیم دایرکتوری کاری داخل کانتینر
WORKDIR /app

# کپی کردن همه فایل‌ها به کانتینر
COPY . .

# نصب کتابخانه‌ها از فایل requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# اجرای فایل اصلی بات
CMD ["python", "main.py"]